### PR TITLE
Disallow URLs from being inputted into the database

### PR DESCRIPTION
**Pull request by natevaut**
- When a URL is inputted into the abstract and the article is submitted, an error is displayed.
- When a URL is put in the body of a request, the request is rejected.

### CODE REVIEW

**Review by 19083522L — DISMISSED** [review]
Non-DOI links are correctly being disregarded

**Review by 19083522L — COMMENTED** [review]
Everything seems to work but git says there is a merge conflict so once that is sorted, then I'll approve

**Comment by natevaut** [comment]
@19083522L  sorted

**Comment by natevaut** [comment]
Merge once approved

**Review by 19083522L — APPROVED** [review]
looks good, seems to work fine

**Pull request merged**
